# Generated by Django 2.1.7 on 2019-03-29 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_agendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAgenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=8, verbose_name='Tipo de Agenda')),
                ('slug', models.SlugField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='agenda',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_agendas.TipoAgenda'),
        ),
    ]
